/**
 * Codegen for `src/stories/_registry.generated.ts` — the static barrel that
 * `lib/stories.ts` reads to build the story registry. Rewritten WHOLE (never
 * appended) whenever a story is committed, so a bad partial write can't leave
 * the build in a broken state.
 *
 * Server-only (node:fs). Dev-only in practice (admin tooling).
 */

import { promises as fs } from "node:fs";
import path from "node:path";
import { STORY_ID_RE } from "./contentFs";

/** kebab/underscore story id → a safe JS identifier (camelCase). */
function toIdent(id: string): string {
  const camel = id.replace(/[^a-zA-Z0-9]+(.)?/g, (_m, c: string | undefined) =>
    c ? c.toUpperCase() : "",
  );
  return /^[a-zA-Z_$]/.test(camel) ? camel : `_${camel}`;
}

/** All story dirs under src/stories that have an `index.ts` (i.e. are
 *  "committed" stories, not bare drafts). Sorted for deterministic output. */
export async function listStoryDirs(): Promise<string[]> {
  const root = path.resolve(process.cwd(), "src", "stories");
  const entries = await fs.readdir(root, { withFileTypes: true });
  const ids: string[] = [];
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    if (!STORY_ID_RE.test(e.name)) continue;
    try {
      await fs.access(path.join(root, e.name, "index.ts"));
    } catch {
      continue; // a draft without an index.ts — not yet committed
    }
    ids.push(e.name);
  }
  return ids.sort();
}

/**
 * Rewrite `_registry.generated.ts` from the story dirs currently on disk that
 * have an index.ts. Returns the list of registered ids.
 */
export async function regenerateRegistry(): Promise<string[]> {
  const ids = await listStoryDirs();

  const importLines = ids
    .map((id) => `import * as ${toIdent(id)} from "./${id}";`)
    .join("\n");
  const entryLines = ids
    .map((id) => `  ${JSON.stringify(id)}: ${toIdent(id)},`)
    .join("\n");

  const content = `// AUTO-GENERATED by the admin story scaffold/commit actions
// (src/app/admin/_actions/generateDraft.ts). Do not edit by hand — your
// changes will be overwritten the next time a story is created or committed.
//
// Each entry maps a storyId to that story's content module
// (src/stories/<id>/index.ts), which exports:
//   { story, charactersFile, monstersFile, itemsFile, encountersFile }
// Static imports keep all content bundled at build time (no runtime fs).

${importLines}

export const STORY_MODULES = {
${entryLines}
} as const;
`;

  const out = path.resolve(
    process.cwd(),
    "src",
    "stories",
    "_registry.generated.ts",
  );
  await fs.writeFile(out, content, "utf-8");
  return ids;
}

/** The standard per-story content module (`index.ts`). Generic — works for
 *  any story id. Written at commit time. */
export function storyIndexSource(): string {
  return `import type { CharactersFile, Story } from "@/types/story";
import {
  CharactersFileSchema,
  EncountersFileSchema,
  ItemsFileSchema,
  MonstersFileSchema,
  StorySchema,
  type EncountersFileT,
  type ItemsFileT,
  type MonstersFileT,
} from "@/data/schemas";

import scenesData from "./scenes.json";
import charactersData from "./characters.json";
import monstersData from "./monsters.json";
import itemsData from "./items.json";
import encountersData from "./encounters.json";

// Validate at module load — fail fast on drift.
export const story: Story = StorySchema.parse(scenesData) as unknown as Story;
export const charactersFile: CharactersFile =
  CharactersFileSchema.parse(charactersData) as unknown as CharactersFile;
export const monstersFile: MonstersFileT = MonstersFileSchema.parse(monstersData);
export const itemsFile: ItemsFileT = ItemsFileSchema.parse(itemsData);
export const encountersFile: EncountersFileT =
  EncountersFileSchema.parse(encountersData);
`;
}
