// AUTO-GENERATED by the admin story scaffold/commit actions
// (src/app/admin/_actions/generateDraft.ts). Do not edit by hand — your
// changes will be overwritten the next time a story is created or committed.
//
// Each entry maps a storyId to that story's content module
// (src/stories/<id>/index.ts), which exports:
//   { story, charactersFile, monstersFile, itemsFile, encountersFile }
// Static imports keep all content bundled at build time (no runtime fs).

import * as wizardOfOz from "./wizard-of-oz";

export const STORY_MODULES = {
  "wizard-of-oz": wizardOfOz,
} as const;
