import { z } from "zod";

/**
 * Schemas for the AI story-generation wizard. Two kinds live here:
 *
 *  1. LLM OUTPUT schemas (Concept / Storyboard / GeneratedCharacters) — fed to
 *     `chat({ schema })`, which converts them to a Gemini `responseJsonSchema`.
 *     These are kept deliberately FLAT and ALL-REQUIRED (no `.optional()` /
 *     `.default()`, arrays instead of records) so structured output stays
 *     robust across providers. "Absent" is represented by an empty string /
 *     empty array, not a missing key.
 *
 *  2. PERSISTED DRAFT schemas (DraftMeta) — written to the draft story dir to
 *     drive wizard resume. These are server-authored, so `.optional()` /
 *     `.default()` are fine.
 *
 * The FINAL artifacts (scenes.json / characters.json) use the existing
 * StorySchema / CharactersFileSchema — these generation schemas are the
 * intermediate scaffolding the wizard maps into those.
 */

// ── Stage 1: Concept ─────────────────────────────────────────────

/** Global art direction — produced once at the concept stage and prepended
 *  verbatim to EVERY image prompt for visual consistency. The generalisation
 *  of the verbatim baselines documented in docs/ASSETS_*.md. */
export const ArtStyleBibleSchema = z.object({
  /** Medium / technique, e.g. "soft watercolor with gouache, paper grain". */
  medium: z.string(),
  /** Palette + colour mood, e.g. "warm earth tones, dusty rose, sage". */
  palette: z.string(),
  /** Line quality, e.g. "loose hand-drawn ink, gentle outlines". */
  lineQuality: z.string(),
  /** Overall mood, e.g. "cozy, hopeful, a little mysterious". */
  mood: z.string(),
  /** Recurring visual motifs (props, shapes, lighting). */
  motifs: z.array(z.string()),
  /** Things to NEVER draw (text in image, scary realism, watermarks…). */
  negative: z.array(z.string()),
});

export const ConceptSchema = z.object({
  title: z.string(),
  /** Tagline. "" when none. */
  subtitle: z.string(),
  /** 2-4 sentences — the tone anchor fed to every later stage. */
  premise: z.string(),
  /** Target age band (years). */
  targetAge: z.object({ min: z.number().int(), max: z.number().int() }),
  /** 2-5 themes. */
  themes: z.array(z.string()),
  /** Language name or code the story is written in (echoed from the brief). */
  language: z.string(),
  estimatedMinutes: z.number().int(),
  artStyleBible: ArtStyleBibleSchema,
});

// ── Stage 2: Storyboard ──────────────────────────────────────────

export const StoryboardBranchSchema = z.object({
  /** Stable slug, unique within the beat. */
  id: z.string(),
  /** Player-facing choice label. */
  label: z.string(),
  /** Target beat id (must reference an existing beat). */
  next: z.string(),
  /** Optional 1-line bridge hint shown after the choice ("" when none). */
  outcomeHint: z.string(),
});

export const StoryboardBeatSchema = z.object({
  /** Stable slug — the beat the scene-pages expand from. */
  id: z.string(),
  /** Editor-only label (not shipped to the player). */
  title: z.string(),
  /** 1-2 lines — what happens in this beat (the story flow). The page stage
   *  decides per-page speaker/setting from this + the cast + premise. */
  synopsis: z.string(),
  /** Terminal beat (the last beat — an ending). */
  isEnding: z.boolean(),
  /** Ending tag label when isEnding ("" otherwise). */
  endingLabel: z.string(),
  /** Always empty — the linear storyboard carries no choices (branching is
   *  authored later in the story graph). Kept for back-compat. */
  branches: z.array(StoryboardBranchSchema),
});

export const StoryboardSchema = z.object({
  /** Beat id the story starts on. */
  startSceneId: z.string(),
  beats: z.array(StoryboardBeatSchema),
});

// ── Stage 3: Characters (LLM output) ─────────────────────────────

/** Role hint guides how the wizard maps a generated character into the real
 *  CharacterSchema (hero → isHero + no persona; narrator → no persona;
 *  companion/npc → persona). Companions are NOT auto-generated by v1 (battles
 *  are added later in the graph), so "companion" is reserved for future use. */
export const GeneratedRoleSchema = z.enum([
  "hero",
  "narrator",
  "npc",
  "companion",
]);

export const GeneratedCharacterSchema = z.object({
  /** Slug id (referenced by scenes). Lowercase kebab-case. */
  id: z.string(),
  /** Display name. */
  name: z.string(),
  role: GeneratedRoleSchema,
  /** Who they are — 1-3 sentences (→ persona.shortBio for npc/companion). */
  bio: z.string(),
  /** How they talk (→ persona.speechStyle). "" for hero/narrator. */
  speechStyle: z.string(),
  /** One-line vocal feel (→ persona.voiceTraits). "" for hero/narrator. */
  voiceTraits: z.string(),
  /** Positive behavioural guidelines (→ persona.dos). */
  dos: z.array(z.string()),
  /** Hard boundaries (→ persona.donts). */
  donts: z.array(z.string()),
  /** One-line illustrator brief — face, hair, outfit, palette, proportions.
   *  Stored in characterArt and fed to the image stage. */
  visualDescription: z.string(),
});

export const GeneratedCharactersSchema = z.object({
  characters: z.array(GeneratedCharacterSchema),
});

// ── Persisted: character art map (visual descriptions) ───────────

export const CharacterArtEntrySchema = z.object({
  id: z.string(),
  visualDescription: z.string(),
});
export const CharacterArtFileSchema = z.object({
  entries: z.array(CharacterArtEntrySchema),
});

// ── Persisted (draft-only): per-scene context for the image stage ─
// Scenes are no longer 1:1 with storyboard beats (the scene stage paginates a
// beat into several pages), so the scene-image prompt can't look a beat up by
// the scene id. The page-expansion records each scene's setting/synopsis and
// its parent beat here so the image prompt has visual context.

export const DraftSceneMetaEntrySchema = z.object({
  setting: z.string(),
  synopsis: z.string(),
  parentBeatId: z.string(),
});
export const DraftSceneMetaSchema = z.object({
  scenes: z.record(z.string(), DraftSceneMetaEntrySchema).default({}),
});

// ── Persisted: draft control state (wizard resume) ───────────────

// Active wizard stages. Legacy drafts may carry "scenes"/"narration"/"images"
// in currentStage — readDraftMeta() normalizes those before parse.
export const DraftStageSchema = z.enum([
  "concept",
  "storyboard",
  "characters",
  "scene",
  "review",
]);

export const StageStatusSchema = z.enum(["pending", "done", "stale"]);

const ItemProgressSchema = z
  .object({
    done: z.array(z.string()).default([]),
    failed: z.array(z.string()).default([]),
  })
  .default({ done: [], failed: [] });

export const DraftMetaSchema = z.object({
  storyId: z.string(),
  status: z.enum(["drafting", "ready", "committed"]).default("drafting"),
  currentStage: DraftStageSchema.default("concept"),
  /** Per-stage status keyed by stage name. */
  stageStatuses: z.record(z.string(), StageStatusSchema).default({}),
  /** The original author brief (for regenerate steering + resume display). */
  brief: z.string().default(""),
  language: z.string().default("en"),
  /** ISO timestamps — stamped by the server actions. */
  createdAt: z.string().default(""),
  updatedAt: z.string().default(""),
  /** Fan-out progress for the per-item stages (resume / partial completion). */
  itemProgress: z
    .object({
      narration: ItemProgressSchema,
      images: ItemProgressSchema,
    })
    .default({
      narration: { done: [], failed: [] },
      images: { done: [], failed: [] },
    }),
});

// ── Inferred types ───────────────────────────────────────────────

export type ArtStyleBibleT = z.infer<typeof ArtStyleBibleSchema>;
export type ConceptT = z.infer<typeof ConceptSchema>;
export type StoryboardBranchT = z.infer<typeof StoryboardBranchSchema>;
export type StoryboardBeatT = z.infer<typeof StoryboardBeatSchema>;
export type StoryboardT = z.infer<typeof StoryboardSchema>;
export type GeneratedRoleT = z.infer<typeof GeneratedRoleSchema>;
export type GeneratedCharacterT = z.infer<typeof GeneratedCharacterSchema>;
export type GeneratedCharactersT = z.infer<typeof GeneratedCharactersSchema>;
export type CharacterArtEntryT = z.infer<typeof CharacterArtEntrySchema>;
export type CharacterArtFileT = z.infer<typeof CharacterArtFileSchema>;
export type DraftSceneMetaEntryT = z.infer<typeof DraftSceneMetaEntrySchema>;
export type DraftSceneMetaT = z.infer<typeof DraftSceneMetaSchema>;
export type DraftStageT = z.infer<typeof DraftStageSchema>;
export type StageStatusT = z.infer<typeof StageStatusSchema>;
export type DraftMetaT = z.infer<typeof DraftMetaSchema>;
